# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Bsv < Formula
  desc "Backstage Entity Visualizer - TUI for exploring catalog-info.yaml files"
  homepage "https://github.com/grahambrooks/bsv"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.9.2/bsv-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "173f787513a16b43f005dc2f5f83ea7b36617e73988bc50eab6e4217759bb060"
    end
    on_intel do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.9.2/bsv-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "37c1b457fc93a683b1be89e77a832e38f10ecc0efef4a34599d72f85e8691363"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.9.2/bsv-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "fa3f8559314c919313fb25f2e8411c145acafbbef5910edd6d347409039e8f72"
    end
    on_intel do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.9.2/bsv-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3cd645646d6163fd6d642f96a06c54b807820785abd241cd8dd2d3c767b12f56"
    end
  end

  def install
    bin.install "bsv"
  end

  test do
    assert_path_exists bin/"bsv"
  end
end
