# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Bsv < Formula
  desc "Backstage Entity Visualizer - TUI for exploring catalog-info.yaml files"
  homepage "https://github.com/grahambrooks/bsv"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.10.1/bsv-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "6589d321228c03e8be22d567f543b67c87db8f3b11e5d7c34aaf64a2f80ba799"
    end
    on_intel do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.10.1/bsv-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "54d1e204994e6a304c8a775023d235565a958d1321d35be51a763c3a79738374"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.10.1/bsv-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "db7b9481f612d948d0e478cc974dee3798a4666b1a084ed6b29cf57e4c17db45"
    end
    on_intel do
      url "https://github.com/grahambrooks/bsv/releases/download/v2026.10.1/bsv-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2e42d3aac801f3c1d4999b3c23e657198147752bfcd9f6a5ff11bb7e617338ef"
    end
  end

  def install
    bin.install "bsv"
  end

  test do
    assert_path_exists bin/"bsv"
  end
end
