# typed: false
# frozen_string_literal: true

# Homebrew formula for bsv, kept in-repo so this repository doubles as a tap.
#
# Install without tapping:
#   brew install https://raw.githubusercontent.com/grahambrooks/bsv/main/Formula/bsv.rb
#
# Or tap this repo and install by name:
#   brew tap grahambrooks/bsv https://github.com/grahambrooks/bsv
#   brew install bsv
#
# This file is generated by scripts/update-packaging.sh on each release.
class Bsv < Formula
  desc "Backstage Entity Visualizer - TUI for exploring catalog-info.yaml files"
  homepage "https://github.com/grahambrooks/bsv"
  version "2026.6.28"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/bsv/releases/download/v#{version}/bsv-aarch64-apple-darwin.tar.gz"
      sha256 "d164cea8674afc278621dd44460a3b213234eed83c72f0d2a4e7c76700d4833b"
    end
    on_intel do
      url "https://github.com/grahambrooks/bsv/releases/download/v#{version}/bsv-x86_64-apple-darwin.tar.gz"
      sha256 "08ff9c9c02157cfa54f80c90b3366934bbfcffa9e7d6168a4611aeb70db6a3c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/grahambrooks/bsv/releases/download/v#{version}/bsv-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1a92d8f4186b244aeecf11f44f48d763264a1870c7ca95a825d64711ab508617"
    end
  end

  def install
    bin.install "bsv"
  end

  test do
    assert_match "bsv #{version}", shell_output("#{bin}/bsv --version")
  end
end
