#!/usr/bin/env bash
# Regenerate the in-repo Homebrew formula and Scoop manifest for a release.
#
# Usage:
#   scripts/update-packaging.sh <version> <checksums-dir>
#
#   <version>        Release version without a leading "v" (e.g. 2026.2.12).
#   <checksums-dir>  Directory containing "<asset>.sha256" files produced by the
#                    release build (each holds "<hash>  <filename>").
#
# Run from the repository root. The release workflow invokes this after building
# all platform artifacts; it can also be run locally to refresh the manifests.
set -euo pipefail

VERSION="${1:?usage: update-packaging.sh <version> <checksums-dir>}"
CHECKSUM_DIR="${2:?usage: update-packaging.sh <version> <checksums-dir>}"
VERSION="${VERSION#v}"

REPO="grahambrooks/bsv"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Read the hash for an asset from "<asset>.sha256"; empty if the file is absent.
read_hash() {
    local file="${CHECKSUM_DIR}/${1}.sha256"
    if [ -f "$file" ]; then
        cut -d' ' -f1 < "$file" | tr -d '[:space:]'
    else
        echo "warning: missing checksum for $1" >&2
        echo ""
    fi
}

mac_arm="$(read_hash "bsv-aarch64-apple-darwin.tar.gz")"
mac_x86="$(read_hash "bsv-x86_64-apple-darwin.tar.gz")"
linux_x86="$(read_hash "bsv-x86_64-unknown-linux-gnu.tar.gz")"
win_x86="$(read_hash "bsv-x86_64-pc-windows-msvc.zip")"

# --- Homebrew formula --------------------------------------------------------
cat > "${ROOT}/Formula/bsv.rb" <<EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for bsv, kept in-repo so this repository doubles as a tap.
#
# Install without tapping:
#   brew install https://raw.githubusercontent.com/${REPO}/main/Formula/bsv.rb
#
# Or tap this repo and install by name:
#   brew tap grahambrooks/bsv https://github.com/${REPO}
#   brew install bsv
#
# This file is generated by scripts/update-packaging.sh on each release.
class Bsv < Formula
  desc "Backstage Entity Visualizer - TUI for exploring catalog-info.yaml files"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/v#{version}/bsv-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/v#{version}/bsv-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_x86}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/${REPO}/releases/download/v#{version}/bsv-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_x86}"
    end
  end

  def install
    bin.install "bsv"
  end

  test do
    assert_match "bsv #{version}", shell_output("#{bin}/bsv --version")
  end
end
EOF

# --- Scoop manifest ----------------------------------------------------------
cat > "${ROOT}/bucket/bsv.json" <<EOF
{
    "version": "${VERSION}",
    "description": "Backstage Entity Visualizer - TUI for exploring catalog-info.yaml files",
    "homepage": "https://github.com/${REPO}",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/${REPO}/releases/download/v${VERSION}/bsv-x86_64-pc-windows-msvc.zip",
            "hash": "${win_x86}",
            "bin": "bsv.exe"
        }
    },
    "checkver": {
        "github": "https://github.com/${REPO}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/${REPO}/releases/download/v\$version/bsv-x86_64-pc-windows-msvc.zip"
            }
        }
    }
}
EOF

echo "Updated Formula/bsv.rb and bucket/bsv.json to version ${VERSION}"
